### PR TITLE
Single run

### PR DESCRIPTION
**Pull request by mmeidlinger**
Feature as requested and specified in https://github.com/khenderick/zfs-snap-manager/issues/32

### CODE REVIEW

**Comment by khenderick** [comment]
Thanks! Can you resolve the conflict?

**Comment by mmeidlinger** [comment]
Sure, can you advice? Guess I would need write access for that:
image

**Comment by khenderick** [comment]
This should be possible by merging khenderick:master back to mmeidlinger:single_run

**Comment by khenderick** [comment]
I'm closing this issue as I unfortunately don't have the time anymore to maintain ZFS Snapshot Manager. I would like to point you towards the awesome tool [zrepl](https://zrepl.github.io/) which has nearly all of ZFS Snapshot Manager's features and much more.

In any case, thanks for being a part of this community.

**Pull request closed without merging**
