### PR TITLE
Zsnapd rework

### PR DESCRIPTION
**Pull request by grantma**
Have a look at this please.  You may find it interesting. Has:

Port to Python3
Fully native systemd support
Better daemon mode support
Better support for logging.  Now configurable.
Move to python3-magcode-core enabled all of the unabove.

Thank you!

### CODE REVIEW

**Comment by genofire** [comment]
i prefer python3 and systemd - any update or comment of this PR?

**Comment by grantma** [comment]
Go and have a look at the zsnapd Debian package in sid.

We use this at my employer for back up! Way improved and works a charm!

**Comment by grantma** [comment]
Hi!

Just reworking packaging in Debian. Running quite well with python 3.7.
Will try 3.9 on Sid shortly to fix any issues.....

Matt

**Comment by grantma** [comment]
Hi!

Have just re python-packaged zsnapd.  python3 setup.py build & install
should now work.

Renamed the scripts directory to zsnap.  There are scripts in the top level
directory of zsnapd.  My install method is to copy the top level directory
into /usr/share as /usr/share/zsnapd, and symlink the scripts to /usr/bin
and /usr/sbin.  This allows you to copy the working directory to your home
directory, symlink that to /usr/share and work and debug the scripts using
the python debugger from the command line.  This works as Python follows
the exec symlinks to find the top level Python execution directory, and
puts that one on the Python modules path.  Unconventional, but makes it a
lot easier when developing.

Git repo is up at: https://github.com/grantma/zsnapd

Let me know how you go.

Best Regards,

Matt Grant

**Comment by pgassmann** [comment]
@grantma your project looks great in the docs and it is packaged in Ubuntu, but I hesitate to introduce it, as I see no updates, no issue tracker and no activity from you on GitHub. Will this project continue to be maintained?

**Comment by khenderick** [comment]
I'm closing this issue as I unfortunately don't have the time anymore to maintain ZFS Snapshot Manager. I would like to point you towards the awesome tool [zrepl](https://zrepl.github.io/) which has nearly all of ZFS Snapshot Manager's features and much more.

In any case, thanks for being a part of this community.

**Pull request closed without merging**
